# config file version
apiVersion: 1

# list of datasources to insert/update
# available in the database
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: db.:5432
    database: fastapi_traefik
    user: fastapi_traefik
    secureJsonData:
      password: 'fastapi_traefik'
    jsonData:
      sslmode: 'disable'